### ISSUE TITLE
Java heap size error 

### ISSUE THREAD

**Issue by enikogabor** [amattioc/SDMX#108]
I use the SDMX Tool from within STATA and want to download a file of  578,725 KB. I get a heap size error, also after allocating 12GB Java memory. (Using the same series key, I am able to download the dataset wth odbc connection).

Error:
java.lang.OutOfMemoryError: Java heap space
        at javax.swing.text.GapContent.allocateArray(GapContent.java:94)
        at javax.swing.text.GapVector.resize(GapVector.java:214)
        at javax.swing.text.GapVector.shiftEnd(GapVector.java:229)
        at javax.swing.text.GapContent.shiftEnd(GapContent.java:345)
        at javax.swing.text.GapVector.open(GapVector.java:201)
        at javax.swing.text.GapVector.replace(GapVector.java:142)
        at javax.swing.text.GapContent.insertString(GapContent.java:132)
        at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:723)
        at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
        at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
        at javax.swing.JTextArea.append(JTextArea.java:477)
        at it.bancaditalia.oss.sdmx.helper.HelperHandler.publish(Unknown Source)
        at java.util.logging.Logger.log(Logger.java:738)
        at java.util.logging.Logger.doLog(Logger.java:765)
        at java.util.logging.Logger.log(Logger.java:788)
        at java.util.logging.Logger.finer(Logger.java:1528)
        at it.bancaditalia.oss.sdmx.parser.v21.CompactDataParser.parse(Unknown Source)
        at it.bancaditalia.oss.sdmx.client.RestSdmxClient.getData(Unknown Source)
        at it.bancaditalia.oss.sdmx.client.RestSdmxClient.getTimeSeries(Unknown Source)
        at it.bancaditalia.oss.sdmx.client.SdmxClientHandler.getSingleTimeSeries(Unknown Source)
        at it.bancaditalia.oss.sdmx.client.SdmxClientHandler.getTimeSeries(Unknown Source)
        at it.bancaditalia.oss.sdmx.client.SdmxClientHandler.getTimeSeries(Unknown Source)
        at it.bancaditalia.oss.sdmx.client.StataClientHandler.getTimeSeries(Unknown Source)
r(5100);

Best,
GTE

**Comment by amattioc** [comment]
Hi @enikogabor

What' the failing query?

**Comment by enikogabor** [comment]
Hi @amattioc 

The query: getdata raw ECB, r(IBSI_RESTR.M.DE.N.A........)     
It is a restricted dataset, M, N, A are fixed dimension values. 
Ideally I would retreive the whole dataset at once, that is  getdata raw ECB, r(IBSI_RESTR.M..N.A........)  , but get the heap size error already for country by country download.
Tried with: stata 64 bit, java 32 bit
Currently trying : stata 64 bit, java 64 bit  (seems to take some time)

**Comment by amattioc** [comment]
Hi @enikogabor 

since this is a restricted dataset I think we'd better continue the troubleshooting by mail. Could send me a note at *attilio.mattiocco[at]bancaditalia.it*?

Best, Attilio

**Comment by amattioc** [comment]
The query, narrowed to single countries, was successful.
